### ISSUE TITLE
ID--GAME-9: l10n translations with Weblate

### ISSUE THREAD

**Issue by JamesClarke7283** [Hacknique/Voxey#10]
**User Story:** ID--GAME-9

As a Non Native English Speaker, I wish to have translations in my native language. This is aimed at providing me with a clear understanding of whats happening in the game.

**Details:**

- **User:** Non native English speaker
- **Functionality:** Translation system with Weblate.
- **Goal:** Have an easy and accessible way to create translations in godot.

**Acceptance Criteria:**

1. Prepare Repository for Weblate
2. Create Weblate account and project on the site.
3. Integrate Weblate into Repository with CI/CD.

**Tasks:**

- [ ] Prepare Repository for weblate
- [ ] Create Weblate account and project on the site.
- [ ] Integrate Weblate into Repository with CI/CD.

**Notes:** None
